export interface Language {
  name: string;
  nativeName: string;
}

export const LANGUAGES: Language[] = [
    { name: 'Abkhazian', nativeName: 'Аҧсуа' },
    { name: 'Afar', nativeName: 'Afaraf' },
    { name: 'Afrikaans', nativeName: 'Afrikaans' },
    { name: 'Akan', nativeName: 'Akan' },
    { name: 'Albanian', nativeName: 'Shqip' },
    { name: 'Amharic', nativeName: 'አማርኛ' },
    { name: 'Arabic', nativeName: 'العربية' },
    { name: 'Aragonese', nativeName: 'Aragonés' },
    { name: 'Armenian', nativeName: 'Հայերեն' },
    { name: 'Assamese', nativeName: 'অসমীয়া' },
    { name: 'Avaric', nativeName: 'Авар мацӀ' },
    { name: 'Avestan', nativeName: 'Avesta' },
    { name: 'Aymara', nativeName: 'Aymar aru' },
    { name: 'Azerbaijani', nativeName: 'Azərbaycan dili' },
    { name: 'Bambara', nativeName: 'Bamanankan' },
    { name: 'Bashkir', nativeName: 'Башҡорт теле' },
    { name: 'Basque', nativeName: 'Euskara' },
    { name: 'Belarusian', nativeName: 'Беларуская' },
    { name: 'Bengali', nativeName: 'বাংলা' },
    { name: 'Bihari', nativeName: 'भोजपुरी' },
    { name: 'Bislama', nativeName: 'Bislama' },
    { name: 'Bosnian', nativeName: 'Bosanski jezik' },
    { name: 'Breton', nativeName: 'Brezhoneg' },
    { name: 'Bulgarian', nativeName: 'Български език' },
    { name: 'Burmese', nativeName: 'ဗမာစာ' },
    { name: 'Catalan', nativeName: 'Català' },
    { name: 'Chamorro', nativeName: 'Chamoru' },
    { name: 'Chechen', nativeName: 'Нохчийн мотт' },
    { name: 'Chichewa', nativeName: 'ChiCheŵa' },
    { name: 'Chinese', nativeName: '中文' },
    { name: 'Chuvash', nativeName: 'Чӑваш чӗлхи' },
    { name: 'Cornish', nativeName: 'Kernewek' },
    { name: 'Corsican', nativeName: 'Corsu' },
    { name: 'Cree', nativeName: 'ᓀᐦᐃᔭᐍᐏᐣ' },
    { name: 'Croatian', nativeName: 'Hrvatski' },
    { name: 'Czech', nativeName: 'Česky' },
    { name: 'Danish', nativeName: 'Dansk' },
    { name: 'Divehi', nativeName: 'ދިވެހި' },
    { name: 'Dutch', nativeName: 'Nederlands' },
    { name: 'Dzongkha', nativeName: 'རྫོང་ཁ' },
    { name: 'English', nativeName: 'English' },
    { name: 'Esperanto', nativeName: 'Esperanto' },
    { name: 'Estonian', nativeName: 'Eesti' },
    { name: 'Ewe', nativeName: 'Eʋegbe' },
    { name: 'Faroese', nativeName: 'Føroyskt' },
    { name: 'Fijian', nativeName: 'Vosa Vakaviti' },
    { name: 'Finnish', nativeName: 'Suomi' },
    { name: 'French', nativeName: 'Français' },
    { name: 'Fula', nativeName: 'Fulfulde' },
    { name: 'Galician', nativeName: 'Galego' },
    { name: 'Georgian', nativeName: 'ქართული' },
    { name: 'German', nativeName: 'Deutsch' },
    { name: 'Greek', nativeName: 'Ελληνικά' },
    { name: 'Guaraní', nativeName: 'Avañeẽ' },
    { name: 'Gujarati', nativeName: 'ગુજરાતી' },
    { name: 'Haitian', nativeName: 'Kreyòl ayisyen' },
    { name: 'Hausa', nativeName: 'Hausa' },
    { name: 'Hebrew', nativeName: 'עברית' },
    { name: 'Herero', nativeName: 'Otjiherero' },
    { name: 'Hindi', nativeName: 'हिन्दी' },
    { name: 'Hiri Motu', nativeName: 'Hiri Motu' },
    { name: 'Hungarian', nativeName: 'Magyar' },
    { name: 'Interlingua', nativeName: 'Interlingua' },
    { name: 'Indonesian', nativeName: 'Bahasa Indonesia' },
    { name: 'Interlingue', nativeName: 'Interlingue' },
    { name: 'Irish', nativeName: 'Gaeilge' },
    { name: 'Igbo', nativeName: 'Asụsụ Igbo' },
    { name: 'Inupiaq', nativeName: 'Iñupiaq' },
    { name: 'Ido', nativeName: 'Ido' },
    { name: 'Icelandic', nativeName: 'Íslenska' },
    { name: 'Italian', nativeName: 'Italiano' },
    { name: 'Inuktitut', nativeName: 'ᐃᓄᒃᑎᑐᑦ' },
    { name: 'Japanese', nativeName: '日本語' },
    { name: 'Javanese', nativeName: 'Basa Jawa' },
    { name: 'Kalaallisut', nativeName: 'Kalaallisut' },
    { name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
    { name: 'Kanuri', nativeName: 'Kanuri' },
    { name: 'Kashmiri', nativeName: 'कश्मीरी' },
    { name: 'Kazakh', nativeName: 'Қазақ тілі' },
    { name: 'Khmer', nativeName: 'ភាសាខ្មែរ' },
    { name: 'Kikuyu', nativeName: 'Gĩkũyũ' },
    { name: 'Kinyarwanda', nativeName: 'Ikinyarwanda' },
    { name: 'Kirghiz', nativeName: 'Кыргыз тили' },
    { name: 'Komi', nativeName: 'Коми кыв' },
    { name: 'Kongo', nativeName: 'KiKongo' },
    { name: 'Korean', nativeName: '한국어' },
    { name: 'Kurdish', nativeName: 'Kurdî' },
    { name: 'Kwanyama', nativeName: 'Kuanyama' },
    { name: 'Latin', nativeName: 'Latine' },
    { name: 'Luxembourgish', nativeName: 'Lëtzebuergesch' },
    { name: 'Ganda', nativeName: 'Luganda' },
    { name: 'Limburgish', nativeName: 'Limburgs' },
    { name: 'Lingala', nativeName: 'Lingála' },
    { name: 'Lao', nativeName: 'ພາສາລາວ' },
    { name: 'Lithuanian', nativeName: 'Lietuvių kalba' },
    { name: 'Luba-Katanga', nativeName: 'Tshiluba' },
    { name: 'Latvian', nativeName: 'Latviešu valoda' },
    { name: 'Manx', nativeName: 'Gaelg' },
    { name: 'Macedonian', nativeName: 'Македонски јазик' },
    { name: 'Malagasy', nativeName: 'Malagasy fiteny' },
    { name: 'Malay', nativeName: 'Bahasa Melayu' },
    { name: 'Malayalam', nativeName: 'മലയാളം' },
    { name: 'Maltese', nativeName: 'Malti' },
    { name: 'Māori', nativeName: 'Te Reo Māori' },
    { name: 'Marathi', nativeName: 'मराठी' },
    { name: 'Marshallese', nativeName: 'Kajin M̧ajeļ' },
    { name: 'Mongolian', nativeName: 'Монгол' },
    { name: 'Nauru', nativeName: 'Ekakairũ Naoero' },
    { name: 'Navajo', nativeName: 'Diné bizaad' },
    { name: 'Norwegian Bokmål', nativeName: 'Norsk bokmål' },
    { name: 'North Ndebele', nativeName: 'IsiNdebele' },
    { name: 'Nepali', nativeName: 'नेपाली' },
    { name: 'Ndonga', nativeName: 'Owambo' },
    { name: 'Norwegian Nynorsk', nativeName: 'Norsk nynorsk' },
    { name: 'Norwegian', nativeName: 'Norsk' },
    { name: 'Nuosu', nativeName: 'ꆈꌠ꒿ Nuosuhxop' },
    { name: 'South Ndebele', nativeName: 'IsiNdebele' },
    { name: 'Occitan', nativeName: 'Occitan' },
    { name: 'Ojibwe', nativeName: 'ᐊᓂᔑᓈᐯᒧᐎᓐ' },
    { name: 'Oromo', nativeName: 'Afaan Oromoo' },
    { name: 'Oriya', nativeName: 'ଓଡ଼ିଆ' },
    { name: 'Ossetian', nativeName: 'Ирон æвзаг' },
    { name: 'Panjabi', nativeName: 'ਪੰਜਾਬੀ' },
    { name: 'Pāli', nativeName: 'पाऴि' },
    { name: 'Persian', nativeName: 'فارسی' },
    { name: 'Polish', nativeName: 'Polski' },
    { name: 'Pashto', nativeName: 'پښتو' },
    { name: 'Portuguese', nativeName: 'Português' },
    { name: 'Quechua', nativeName: 'Runa Simi' },
    { name: 'Romansh', nativeName: 'Rumantsch grischun' },
    { name: 'Kirundi', nativeName: 'KiRundi' },
    { name: 'Romanian', nativeName: 'Română' },
    { name: 'Russian', nativeName: 'Русский язык' },
    { name: 'Sanskrit', nativeName: 'संस्कृतम्' },
    { name: 'Sardinian', nativeName: 'Sardu' },
    { name: 'Sindhi', nativeName: 'सिन्धी' },
    { name: 'Northern Sami', nativeName: 'Davvisámegiella' },
    { name: 'Samoan', nativeName: 'Gagana faa Samoa' },
    { name: 'Sango', nativeName: 'Yângâ tî sängö' },
    { name: 'Serbian', nativeName: 'Српски језик' },
    { name: 'Scottish Gaelic', nativeName: 'Gàidhlig' },
    { name: 'Shona', nativeName: 'ChiShona' },
    { name: 'Sinhala', nativeName: 'සිංහල' },
    { name: 'Slovak', nativeName: 'Slovenčina' },
    { name: 'Slovene', nativeName: 'Slovenščina' },
    { name: 'Somali', nativeName: 'Soomaaliga' },
    { name: 'Southern Sotho', nativeName: 'Sesotho' },
    { name: 'Spanish', nativeName: 'Español' },
    { name: 'Sundanese', nativeName: 'Basa Sunda' },
    { name: 'Swahili', nativeName: 'Kiswahili' },
    { name: 'Swati', nativeName: 'SiSwati' },
    { name: 'Swedish', nativeName: 'Svenska' },
    { name: 'Tamil', nativeName: 'தமிழ்' },
    { name: 'Telugu', nativeName: 'తెలుగు' },
    { name: 'Tajik', nativeName: 'Тоҷикӣ' },
    { name: 'Thai', nativeName: 'ไทย' },
    { name: 'Tigrinya', nativeName: 'ትግርኛ' },
    { name: 'Tibetan', nativeName: 'བོད་ཡིག' },
    { name: 'Turkmen', nativeName: 'Türkmen' },
    { name: 'Tagalog', nativeName: 'Wikang Tagalog' },
    { name: 'Tswana', nativeName: 'Setswana' },
    { name: 'Tonga', nativeName: 'Faka Tonga' },
    { name: 'Turkish', nativeName: 'Türkçe' },
    { name: 'Tsonga', nativeName: 'Xitsonga' },
    { name: 'Tatar', nativeName: 'Татарча' },
    { name: 'Twi', nativeName: 'Twi' },
    { name: 'Tahitian', nativeName: 'Reo Tahiti' },
    { name: 'Uighur', nativeName: 'Uyƣurqə' },
    { name: 'Ukrainian', nativeName: 'Українська' },
    { name: 'Urdu', nativeName: 'اردو' },
    { name: 'Uzbek', nativeName: 'Oʻzbek' },
    { name: 'Venda', nativeName: 'Tshivenḓa' },
    { name: 'Vietnamese', nativeName: 'Tiếng Việt' },
    { name: 'Volapük', nativeName: 'Volapük' },
    { name: 'Walloon', nativeName: 'Walon' },
    { name: 'Welsh', nativeName: 'Cymraeg' },
    { name: 'Wolof', nativeName: 'Wollof' },
    { name: 'Western Frisian', nativeName: 'Frysk' },
    { name: 'Xhosa', nativeName: 'IsiXhosa' },
    { name: 'Yiddish', nativeName: 'ייִדיש' },
    { name: 'Yoruba', nativeName: 'Yorùbá' },
    { name: 'Zhuang', nativeName: 'Saɯ cueŋƅ' },
    { name: 'Zulu', nativeName: 'IsiZulu' },
];
